import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const superMaples = localFont({
  src: "../../public/fonts/SuperMaples-2vR2w.ttf",
  variable: "--font-super-maples",
});

const punky = localFont({
  src: "../../public/fonts/VeryVeryPunkFont-ZpZ0K.ttf",
  variable: "--font-punky",
});

const superReduce = localFont({
  src: "../../public/fonts/SuperReduce-Ealv8.ttf",
  variable: "--font-super-reduce",
});

const wkwk = localFont({
  src: "../../public/fonts/Wkwk-2O988.otf",
  variable: "--font-wkwk",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ReWrySe",
  description: "Generated by create next app",
  icons: {
    icon: "/naver-logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" as="image" href="/assets/chat2.png" />
        <link rel="preload" as="image" href="/assets/files5.png" />
        <link rel="preload" as="image" href="/assets/sea9.png" />
        <link rel="preload" as="image" href="/assets/login4.png" />
      </head>
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${superMaples.variable} 
          ${punky.variable} 
          ${superReduce.variable} 
          ${wkwk.variable}
          antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
